### ISSUE TITLE
3 задачи - 3 дня

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/Competitive-programming#11]
Решить 3 задачи:
- [Выборка из четных индексов](https://practice.geeksforgeeks.org/problems/print-alternate-elements-of-an-array/1?page=1&difficulty[]=-2&sortBy=submissions)
- [Поиск второго наибольшего](https://practice.geeksforgeeks.org/problems/second-largest3735/1?page=1&difficulty[]=-2&sortBy=submissions)
- Самое сложное - [написать последовательности чисел](https://practice.geeksforgeeks.org/problems/print-the-pattern-set-1/1?page=1&difficulty[]=-2&sortBy=submissions)

**Comment by FedorKatta** [comment]
https://practice.geeksforgeeks.org/problems/print-alternate-elements-of-an-array/1?page=1&difficulty%5B%5D=-2&sortBy=submissions - выборка четных чисел
https://practice.geeksforgeeks.org/problems/second-largest3735/1?page=1&difficulty%5B%5D=-2&sortBy=submissions - поиск второго наибольшего
https://practice.geeksforgeeks.org/problems/print-the-pattern-set-1/1?page=1&difficulty%5B%5D=-2&sortBy=submissions - написать последовательность чисел.
