### ISSUE TITLE
Проработка рекурсии

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/Competitive-programming#13]
Дедлайн - 25 сентбря
Выполнить задачу на [сдвинг элементов в списке](https://practice.geeksforgeeks.org/problems/shuffle-integers2401/1?page=1&difficulty[]=-1&category[]=Recursion&sortBy=submissions)

Дедлайн - 28 сентября
Выполнить задачу на [последовательность жонглера](https://practice.geeksforgeeks.org/problems/juggler-sequence3930/1?page=1&difficulty[]=-1&category[]=Recursion&sortBy=submissions)

Для закрытия этой задачи нужно добавить 2 функции в файл `recursions.py`, которые выполняют эти задачи

**Comment by FedorKatta** [comment]
Всё сделано.
