### ISSUE TITLE
Не надо ничего решать

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/Competitive-programming#35]
Надо просто прочитать 2 артикля:
[Принцип голубей](https://www.geeksforgeeks.org/discrete-mathematics-the-pigeonhole-principle/)
[Деление на 10^9+7](https://www.geeksforgeeks.org/modulo-1097-1000000007/)
В кратце рассказать, про что там было написано. Мб задам пару вопросов

**Comment by FedorKatta** [comment]
(x ? y) % 10^9+7 != x % 10^9+7 ? y % 10^9+7
