### ISSUE TITLE
2 задачу на массивы

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/Competitive-programming#4]
1) Решить задачу на [поиск большего числа](https://practice.geeksforgeeks.org/problems/peak-element/1?page=1&category[]=Arrays&category[]=Strings&sortBy=submissions)

2) Решить задачу на [поиск суммы подмассива в массиве](https://practice.geeksforgeeks.org/problems/subarray-with-given-sum-1587115621/1?page=1&category[]=Arrays&category[]=Strings&sortBy=submissions)

**Comment by FedorKatta** [comment]
1 задача решена( снова нечестно )

**Comment by FedorKatta** [comment]
решил на 75%, остальное неважно

**Comment by FedorKatta** [comment]
https://practice.geeksforgeeks.org/viewSol.php?subId=2f11993afd87825c987eeb8ff648035a&pid=700512&user=fedorkatta

**Comment by FedorKatta** [comment]
все решено
