### ISSUE TITLE
Сортировки

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/Competitive-programming#5]
Сделать 2 алгоритма сортировки для списка чисел
- Bubble sort
- Counting sort

После реализации загрузить код на гитхаб (через pull request)

**Comment by FedorKatta** [comment]
и шо это, а где дз?

**Comment by FedorKatta** [comment]
я случайно

**Comment by Zener085** [comment]
Это дз - учи сортировки

**Comment by FedorKatta** [comment]
ок
